apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: ngtrantan99/reverseproxy:v3
        name: reverseproxy
        resources: {}
        ports:
          - containerPort: 8080
status: {}
